/** Declaration file generated by dts-gen */

export function compare(a: any, b: any): any;

export function compareCIDR(a: any, b: any): any;

export function createAddrRange(begin: any, end: any): any;

export function createCIDR(addr: any, len: any): any;

export function parse(input: any): any;
