name: Lint
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '3 0 * * SUN'
  workflow_dispatch:
permissions: {}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 22
      - name: Check that package-lock.json is valid JSON
        run: jq empty package-lock.json
      - name: Install npm packages
        run: npm ci
      - name: Run eslint
        run: npm run lint
      - name: Run prettier
        run: npm run prettier:ci
      - name: Test compile
        run: npx tsc --noEmit
