name: Run tests
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '3 2 * * SUN'
permissions: {}
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [22, 24]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: true
          persist-credentials: false
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.version }}
      - run: npm ci
      - run: npm test --coverage
      - run: npm run build
      - run: npm run build:docs
      - run: npm link
      - run: npm ci
        working-directory: e2e/js
      - run: npm link '@maxmind/geoip2-node'
        working-directory: e2e/js
      - run: npx jest
        working-directory: e2e/js
        env:
          NODE_OPTIONS: --experimental-vm-modules
      - run: npm ci
        working-directory: e2e/ts
      - run: npm link '@maxmind/geoip2-node'
        working-directory: e2e/ts
      - run: npx jest
        working-directory: e2e/ts
        env:
          NODE_OPTIONS: --experimental-vm-modules
